backend:
  name: git-gateway

media_folder: "/static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "content/_index.md"
        label: "Page d'accueil"
        name: "home"
        widget: list
        fields:
          - { label: "Intro", name: "body", widget: "markdown" }
          - { label: "Image intro", name: "intro_image", widget: "image" }
          - label: "Images slider"
            name: "carousel_images"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image" }
              - {label: "Texte du slide", name: "text", widget: "text", required: false}

      - file: "content/clients/_index.md"
        label: "Page clients"
        name: "clients"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "En-tete", name: "body", widget: "text" }

      - file: "content/contact/_index.md"
        label: "Contact"
        name: "Contact"
        widget: "list"
        fields:
          - {label: "En-tete", name: "body", widget: "text", required: true}
          - {label: "Telephone Principal", name: "principal_phone", widget: "string", required: true}
          - label: "Telephone"
            name: "phones"
            create: true,
            delete: true
            widget: "list"
            fields:
              - {label: "Telephone", name: "phone", widget: "string"}
          - label: "Adresses"
            name: "addresses"
            create: true,
            delete: true
            widget: "list"
            fields:
              - {label: "Adresse", name: "address", widget: "string"}
          - label: "Emails"
            name: "emails"
            create: true,
            delete: true
            widget: "list"
            fields:
              - {label: "Email", name: "email", widget: "string"}


  - name: "Projects"
    label: "Projets"
    editor:
      preview: false
    label_singular: "Projet"
    folder: "content/project"
    create: true,
    delete: true
    fields:
      - { label: "Nom du projet", name: "title", widget: "string" }
      - { label: "type", name: "type", widget: "hidden", default: "project" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Phase", name: "phase", widget: "string" }
      - { label: "Date de Livraison", name: "date_livraison", widget: "string" }
      - { label: "Delai", name: "delai", widget: "string" }
      - { label: "Nombre de Logements", name: "nombre_logement", widget: "string" }
      - { label: "Etat d'avancement", name: "etat_avancement", widget: "string" }
      - { label: "description", name: "description", widget: "text" }
      - label: "Images Additionnelles"
        name: "images"
        create: true,
        delete: true
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "string"}
      - { label: "Texte", name: "body", widget: "markdown" }

  - name: "client"
    label: "Clients"
    editor:
      preview: false
    label_singular: "Client"
    folder: "content/clients"
    create: true,
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Type", name: "type", widget: "hidden", default: "client"}

  - name: "pack"
    label: "Packs"
    editor:
      preview: false
    label_singular: "Pack"
    folder: "content/pack"
    create: true,
    delete: true
    widget: "list"
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}-{{slug}}"
    fields:
      - {label: "Nom du Pack", name: "title", widget: "string", required: true}
      - {label: "type", name: "type", widget: "hidden", default: "pack"}
      - {label: "Breve Description", name: "description", widget: "text", required: true}
      - label: "Caracteristiques"
        name: "features"
        create: true,
        delete: true
        widget: "list"
        fields:
          - {label: "Caracteristique", name: "feature", widget: "string"}

