backend:
  name: git-gateway

media_folder: "/static/img"
public_folder: "/img"

editor:
  preview: false

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Page d'accueil"
        name: "home"
        fields:
          - { label: "Intro", name: "body", widget: "markdown" }
          - { label: "Image intro", name: "intro_image", widget: "image" }
          - label: "Images slider"
            name: "carousel_images"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Texte du slide", name: "text", widget: "text", required: false}

      - file: "content/contact/_index.md"
        label: "Contact"
        name: "contact"
        fields:
          - label: "N Téléphone"
            name: "phones"
            widget: "list"
            field: { label: "N Téléphone", name: "phone", widget: "string" }

          - label: "Emails"
            name: "emails"
            widget: "list"
            field: { label: "Adresse Email", name: "email", widget: "string" }

          - label: "Adresses Postales"
            name: "addresses"
            widget: "list"
            field: { label: "Adresse", name: "address", widget: "string" }

          - label: "En-tete"
            name: "body"
            widget: "text"
            allow_add: false

  - name: "Projects"
    label: "Projets"
    label_singular: "Projet"
    folder: "content/project"
    create: true,
    delete: true
    fields:
      - { label: "Nom du projet", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "description", name: "description", widget: "text" }
      - { label: "Texte", name: "body", widget: "markdown" }

  - name: "client"
    label: "Clients"
    label_singular: "Client"
    folder: "content/client"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Type", name: "type", widget: "hidden", default: "client"}

